name: auto_common_spec
app_type: rhoelements
version: 1.0
vendor: rhomobile
build: release
bbver: 4.6
applog: rholog.txt
iphone:
  configuration: "Release"
  sdk: "iphoneos8.2"
  provisionprofile: "iOS Team Provisioning Profile"
  production:
    mobileprovision_file: "./production/iOS_Team_Provisioning_Profile.mobileprovision"
    certificate_file: "./production/Certificatesnew.p12"
    certificate_password: "Rhoelements10"
  codesignidentity: "iPhone Developer"
  BundleIdentifier: "com.rhomobile.autocommonspec"
  BundleURLScheme: "autocommonspec"
  extensions: ["sensor", "screenorientation", "audiocapture", "barcode"]
wp:
  productid: 'b6479381-42a8-0130-78de-3caec51bd50e'
symbian:
  uid: '0xe1a1ef92'
android:
  version: 4.2.2
  extensions: ["barcode", "screenorientation", "cardreader", "indicators", "sensor", "websocket", "eventsource", "audiocapture", "screenorientation", "mediacapture"]
  capabilities:
  - native_browser
wm:
  #webkit_outprocess: 1
  #use_shared_runtime: yes
  #sdk: MC3000c50b (ARMV4I)
  sdk: "Windows Mobile 6.5.3 Professional DTK (ARMV4I)"
  extensions: ["barcode", "screenorientation", "cardreader", "indicators", "sensor", "audiocapture"]
#capabilities:
#- non_motorola_device

extensions: ["logCapture"]
